package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Applicant generated by hbm2java
 */
public class Applicant implements java.io.Serializable {

	private String id;
	private Person person;
	private Status status;
	private Integer grade;
	private Set apptostudates = new HashSet(0);

	public Applicant() {
	}

	public Applicant(String id, Person person) {
		this.id = id;
		this.person = person;
	}

	public Applicant(String id, Person person, Status status, Integer grade,
			Set apptostudates) {
		this.id = id;
		this.person = person;
		this.status = status;
		this.grade = grade;
		this.apptostudates = apptostudates;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Integer getGrade() {
		return this.grade;
	}

	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	public Set getApptostudates() {
		return this.apptostudates;
	}

	public void setApptostudates(Set apptostudates) {
		this.apptostudates = apptostudates;
	}

}
