package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Apptostudate generated by hbm2java
 */
public class Apptostudate implements java.io.Serializable {

	private ApptostudateId id;
	private Student student;
	private Applicant applicant;
	private Date time;

	public Apptostudate() {
	}

	public Apptostudate(ApptostudateId id, Student student,
			Applicant applicant, Date time) {
		this.id = id;
		this.student = student;
		this.applicant = applicant;
		this.time = time;
	}

	public ApptostudateId getId() {
		return this.id;
	}

	public void setId(ApptostudateId id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(Applicant applicant) {
		this.applicant = applicant;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
