package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * ApptostudateId generated by hbm2java
 */
public class ApptostudateId implements java.io.Serializable {

	private String appId;
	private String stuId;

	public ApptostudateId() {
	}

	public ApptostudateId(String appId, String stuId) {
		this.appId = appId;
		this.stuId = stuId;
	}

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public String getStuId() {
		return this.stuId;
	}

	public void setStuId(String stuId) {
		this.stuId = stuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ApptostudateId))
			return false;
		ApptostudateId castOther = (ApptostudateId) other;

		return ((this.getAppId() == castOther.getAppId()) || (this.getAppId() != null
				&& castOther.getAppId() != null && this.getAppId().equals(
				castOther.getAppId())))
				&& ((this.getStuId() == castOther.getStuId()) || (this
						.getStuId() != null && castOther.getStuId() != null && this
						.getStuId().equals(castOther.getStuId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAppId() == null ? 0 : this.getAppId().hashCode());
		result = 37 * result
				+ (getStuId() == null ? 0 : this.getStuId().hashCode());
		return result;
	}

}
