package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private int id;
	private Student student;
	private Status status;
	private String reason;
	private Date timeEvent;

	public Event() {
	}

	public Event(int id, Student student, Status status, Date timeEvent) {
		this.id = id;
		this.student = student;
		this.status = status;
		this.timeEvent = timeEvent;
	}

	public Event(int id, Student student, Status status, String reason,
			Date timeEvent) {
		this.id = id;
		this.student = student;
		this.status = status;
		this.reason = reason;
		this.timeEvent = timeEvent;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public Date getTimeEvent() {
		return this.timeEvent;
	}

	public void setTimeEvent(Date timeEvent) {
		this.timeEvent = timeEvent;
	}

}
