package com.example.model;
// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private String cmt;
	private School school;
	private String name;
	private Date birthday;
	private String address;
	private Set applicants = new HashSet(0);
	private Set students = new HashSet(0);

	public Person() {
	}

	public Person(String cmt) {
		this.cmt = cmt;
	}

	public Person(String cmt, School school, String name, Date birthday,
			String address, Set applicants, Set students) {
		this.cmt = cmt;
		this.school = school;
		this.name = name;
		this.birthday = birthday;
		this.address = address;
		this.applicants = applicants;
		this.students = students;
	}

	public String getCmt() {
		return this.cmt;
	}

	public void setCmt(String cmt) {
		this.cmt = cmt;
	}

	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getApplicants() {
		return this.applicants;
	}

	public void setApplicants(Set applicants) {
		this.applicants = applicants;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
