package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * School generated by hbm2java
 */
public class School implements java.io.Serializable {

	private String sid;
	private String sname;
	private Set persons = new HashSet(0);

	public School() {
	}

	public School(String sid, String sname) {
		this.sid = sid;
		this.sname = sname;
	}

	public School(String sid, String sname, Set persons) {
		this.sid = sid;
		this.sname = sname;
		this.persons = persons;
	}

	public String getSid() {
		return this.sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Set getPersons() {
		return this.persons;
	}

	public void setPersons(Set persons) {
		this.persons = persons;
	}

}
