package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private String id;
	private Person person;
	private Status status;
	private Set apptostudates = new HashSet(0);
	private Set events = new HashSet(0);
	private Resource resource;
	private Set subjects = new HashSet(0);

	public Student() {
	}

	public Student(String id, Person person, Status status) {
		this.id = id;
		this.person = person;
		this.status = status;
	}

	public Student(String id, Person person, Status status, Set apptostudates,
			Set events, Resource resource, Set subjects) {
		this.id = id;
		this.person = person;
		this.status = status;
		this.apptostudates = apptostudates;
		this.events = events;
		this.resource = resource;
		this.subjects = subjects;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Set getApptostudates() {
		return this.apptostudates;
	}

	public void setApptostudates(Set apptostudates) {
		this.apptostudates = apptostudates;
	}

	public Set getEvents() {
		return this.events;
	}

	public void setEvents(Set events) {
		this.events = events;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public Set getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set subjects) {
		this.subjects = subjects;
	}

}
