package com.example.model;

// Generated Aug 23, 2015 10:23:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TimesubjectId generated by hbm2java
 */
public class TimesubjectId implements java.io.Serializable {

	private String subId;
	private String classId;
	private String room;
	private Date beginDate;
	private Date endDate;
	private String notes;

	public TimesubjectId() {
	}

	public TimesubjectId(String subId, String classId, String room,
			Date beginDate, Date endDate, String notes) {
		this.subId = subId;
		this.classId = classId;
		this.room = room;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.notes = notes;
	}

	public String getSubId() {
		return this.subId;
	}

	public void setSubId(String subId) {
		this.subId = subId;
	}

	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimesubjectId))
			return false;
		TimesubjectId castOther = (TimesubjectId) other;

		return ((this.getSubId() == castOther.getSubId()) || (this.getSubId() != null
				&& castOther.getSubId() != null && this.getSubId().equals(
				castOther.getSubId())))
				&& ((this.getClassId() == castOther.getClassId()) || (this
						.getClassId() != null && castOther.getClassId() != null && this
						.getClassId().equals(castOther.getClassId())))
				&& ((this.getRoom() == castOther.getRoom()) || (this.getRoom() != null
						&& castOther.getRoom() != null && this.getRoom()
						.equals(castOther.getRoom())))
				&& ((this.getBeginDate() == castOther.getBeginDate()) || (this
						.getBeginDate() != null
						&& castOther.getBeginDate() != null && this
						.getBeginDate().equals(castOther.getBeginDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this
						.getEndDate() != null && castOther.getEndDate() != null && this
						.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getNotes() == castOther.getNotes()) || (this
						.getNotes() != null && castOther.getNotes() != null && this
						.getNotes().equals(castOther.getNotes())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSubId() == null ? 0 : this.getSubId().hashCode());
		result = 37 * result
				+ (getClassId() == null ? 0 : this.getClassId().hashCode());
		result = 37 * result
				+ (getRoom() == null ? 0 : this.getRoom().hashCode());
		result = 37 * result
				+ (getBeginDate() == null ? 0 : this.getBeginDate().hashCode());
		result = 37 * result
				+ (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37 * result
				+ (getNotes() == null ? 0 : this.getNotes().hashCode());
		return result;
	}

}
